config/routes.rb
Rails.application.routes.draw do

  get 'language/:ln' => 'languages#change', as: :language

  root 'welcome#index'

  get 'welcome/index'
  get 'contact' => 'contact#index', as: :contact

  resources :reservations, only: [:new, :create]
  resources :rooms, only: [:index, :show]
  resources :user_sessions
  resources :users

  namespace :admin do
   resources :reservations, except: [:new, :create]
   resources :rooms, except: [:index, :show]
  end

  get 'user' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
  
end

app/models/reservation.rb
class DateValidator < ActiveModel::Validator
   def validate reservation
      @beg, @end = reservation.beginning, reservation.end

      num_people = reservation.adults_number.to_i + reservation.children_number.to_i

      @rooms = Room.all
      reservation.errors[:base] << "There is no free place in our Hostel at these dates." if free_places(@beg, @end, num_people)
   end

   def free_places beg_date, end_date, num_people
      Reservation.free_rooms(beg_date, end_date, num_people).empty?
   end
end

class PeopleNumValidator < ActiveModel::Validator
   def validate reservation
      adults_num = reservation.adults_number
      children_num = reservation.children_number

      reservation.errors[:base] << "Incorrect number of people." unless correct_number_of_people adults_num, children_num
   end

   def correct_number_of_people adults_num, children_num
      adults = adults_num.is_a?(Integer) && adults_num > 0
      children = (children_num.is_a?(Integer) || children_num.is_a?(NilClass)) && children_num.to_i >= 0

      adults && children
   end
end

class Reservation < ActiveRecord::Base
   belongs_to :room
   attr_writer :current_step

   validates_presence_of :adults_number, :beginning, :end, if: :date_step?
   validates_presence_of :first_name, :surname, :phone_number, :email_address, if: :personal_step?
   validates :phone_number, format: {with: /\+\d{12}/}
   validates_presence_of :room_id, if: :room_step?
   validates_with DateValidator, if: :date_step?
   validates_with PeopleNumValidator, if: :date_step?

   def steps
      %w[date personal room hidden]
   end

   def current_step
      @current_step || steps.first
   end

   def next_step
      self.current_step = steps[ steps.index(current_step) + 1 ]
   end

   def previous_step
      self.current_step = steps[ steps.index(current_step) - 1]
   end

   def first_step?
      current_step == steps.first
   end

   def last_step?
      current_step == steps.last
   end

   # Array of rooms in which there are free beds
   # When there is no free beds or even one of 
   # arguments is nil - It returns []
   def self.free_rooms beg_date, end_date, num_people
      return [] if [beg_date, end_date, num_people].any?{|x| x == nil}

      Room.all.map do |room|
         room if (beg_date..end_date).all? do |date|
            rooms_beds_occupied = room.reservations.map {|res| res.adults_number + res.children_number.to_i if date > res.beginning && date < res.end}.compact.reduce(:+).to_i

            room.beds_number - rooms_beds_occupied >= num_people
         end
      end.compact
   end

private
   def personal_step?
      current_step == 'personal'
   end

   def date_step?
      current_step == 'date'
   end

   def room_step?
      current_step == 'room'
   end
      
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < Admin::BaseController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/1/edit
  def edit
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to admin_reservation_path @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end 
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to admin_reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:first_name, :surname, :adults_number, :children_number, :beginning, :end, :discount, :room_id)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  # GET /reservations/new
  def new
    session[:reservation_params] ||= {}
    @reservation = Reservation.new(session[:reservation_params])
    @reservation.current_step = session[:reservation_step]

    @rooms = Room.all
  end

  # POST /reservations
  #
  def create
    session[:reservation_params].deep_merge!(params[:reservation]) if params[:reservation]
    @reservation = Reservation.new(session[:reservation_params])
    @reservation.current_step = session[:reservation_step]
    
    @rooms = Reservation.free_rooms(@reservation.beginning, @reservation.end, @reservation.adults_number.to_i + @reservation.children_number.to_i)
    
    if @reservation.valid?
      if params[:back_button]
         @reservation.previous_step
      elsif @reservation.last_step?
         @reservation.save
      else
         @reservation.next_step
      end
      session[:reservation_step] = @reservation.current_step
    end

    if @reservation.new_record?
       render :new
    else
       session[:reservation_params] = session[:reservation_step] = nil
       redirect_to :root
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:first_name, :surname, :adults_number, :children_number, :beginning, :end, :discount, :room_id)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/admin/reservations/_date_step.html.erb
<div class="field">
   <%= f.label :adults_number %><br>
   <%= f.number_field :adults_number %>
</div>
<div class="field">
   <%= f.label :children_number %><br>
   <%= f.number_field :children_number %>
</div>
<div class="field">
   <%= f.label :dates %>
   <div class="input-daterange input-group" id="datepicker">
      <%= f.text_field :beginning, class: "input-sm form-control" %>
      <span class="input-group-addon">to</span>
      <%= f.text_field :end, class: "input-sm form-control" %>
   </div>
</div>

<%= javascript_tag do %>
   var rooms_class = '<%= @rooms.class %>'
<% end %>

app/views/admin/reservations/_form.html.erb
<%= form_for([:admin, @reservation]) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<%= render "#{@reservation.current_step}_step", f: f %>

  <div class="actions">
   <%= f.submit 'Back', name: 'back_button' unless @reservation.first_step? %>
   <%= f.submit 'Confirm' if @reservation.last_step? %>
   <%= f.submit 'Continue' unless @reservation.last_step? %>
  </div>
<% end %>

app/views/admin/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_reservation_path(@reservation) %> |
<%= link_to 'Back', admin_reservations_path %>

app/views/admin/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reservations</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Surname</th>
      <th>email</th>
      <th>Phone number</th>
      <th>Adults number</th>
      <th>Children number</th>
      <th>Beginning</th>
      <th>End</th>
      <th>Discount</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.first_name %></td>
        <td><%= reservation.surname %></td>
        <td><%= reservation.email_address %></td>
        <td><%= reservation.phone_number %></td>
        <td><%= reservation.adults_number %></td>
        <td><%= reservation.children_number.to_i %></td>
        <td><%= reservation.beginning %></td>
        <td><%= reservation.end %></td>
        <td><%= reservation.discount %></td>
        <td><%= reservation.room.room_number unless reservation.room == nil %></td>
        <td><%= link_to 'Show', admin_reservation_path(reservation) %></td>
        <td><%= link_to 'Edit', edit_admin_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', admin_reservation_path(reservation), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/admin/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @reservation.first_name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @reservation.surname %>
</p>

<p>
  <strong>Adults number:</strong>
  <%= @reservation.adults_number %>
</p>

<p>
  <strong>Children number:</strong>
  <%= @reservation.children_number %>
</p>

<p>
  <strong>Beginning:</strong>
  <%= @reservation.beginning %>
</p>

<p>
  <strong>End:</strong>
  <%= @reservation.end %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @reservation.discount %>
</p>

<p>
  <strong>Room:</strong>
  <%= @reservation.room.room_number unless @reservation.room == nil %>
</p>

<%= link_to 'Edit', edit_admin_reservation_path(@reservation) %> |
<%= link_to 'Back', admin_reservations_path %>