config/routes.rb
Rails.application.routes.draw do

  get 'language/:ln' => 'languages#change', as: :language

  root 'welcome#index'

  get 'welcome/index'
  get 'contact' => 'contact#index', as: :contact

  resources :reservations, only: [:new, :create]
  resources :rooms, only: [:index, :show]
  resources :user_sessions
  resources :users

  namespace :admin do
   resources :reservations, except: [:new, :create]
   resources :rooms, except: [:index, :show]
  end

  get 'user' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
  
end

app/models/room.rb
class Room < ActiveRecord::Base
   validates :room_number, uniqueness: true
   has_many :reservations, dependent: :destroy

   accepts_nested_attributes_for :reservations
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < Admin::BaseController
  before_action :set_room, only: [:edit, :update, :destroy]

  # GET /rooms/new
  def new
    @room = Room.new
    @room.reservations.build
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_number, :beds_number, :price_per_adult, :price_per_child)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Room number</th>
      <th>Beds number</th>
      <th>Price per adult</th>
      <th>Price per child</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_number %></td>
        <td><%= room.beds_number %></td>
        <td><%= room.price_per_adult %></td>
        <td><%= room.price_per_child %></td>
        <td><%= link_to 'Show', room %></td>
        <% if current_user %>
         <td><%= link_to 'Edit', edit_admin_room_path(room) %></td>
         <td><%= link_to 'Destroy', admin_room_path(room), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_admin_room_path if current_user %>

app/views/rooms/new.html.erb
<%= form_for @room do |f| %>
   <div class='room_form'>
      <div class='container'>
         <p>
            <%= f.label :room_number %><br>
            <%= f.text_field :room_number %>
         </p>

         <p>
            <%= f.label :beds_number %><br>
            <%= f.text_field :beds_number %>
         </p>

         <p>
            <%= f.label :price_per_adult %><br>
            <%= f.text_field :price_per_adult %>
         </p>

         <p>
            <%= f.label :price_per_child %><br>
            <%= f.text_field :price_per_child %>
         </p>

         <p>
            <%= f.submit %>
         </p>
      </div>
   <div>
<% end %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room number:</strong>
  <%= @room.room_number %>
</p>

<p>
  <strong>Beds number:</strong>
  <%= @room.beds_number %>
</p>

<p>
  <strong>Price per adult:</strong>
  <%= @room.price_per_adult %>
</p>

<p>
  <strong>Price per child:</strong>
  <%= @room.price_per_child %>
</p>

<%= link_to 'Edit', edit_admin_room_path(@room) if current_user %>  
<%= link_to 'Back', rooms_path %>