config/routes.rb
Rails.application.routes.draw do

  get 'language/:ln' => 'languages#change', as: :language

  root 'welcome#index'

  get 'welcome/index'
  get 'contact' => 'contact#index', as: :contact

  resources :reservations, only: [:new, :create]
  resources :rooms, only: [:index, :show]
  resources :user_sessions
  resources :users

  namespace :admin do
   resources :reservations, except: [:new, :create]
   resources :rooms, except: [:index, :show]
  end

  get 'user' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_language

private

  def accepted_language
   #read from HTTP request
   :pl
  end

  def set_language
    I18n.locale = session[:language] || accepted_language
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<hr>

app/views/application/_header.html.haml
%nav.navbar.navbar-default
   .container-fluid
      .navbar-header
         %button.navbar-toggle{'type'=>'button', 'data-toggle'=>'collapse', 'data-target'=>'#myNavbar'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
         = link_to 'Hostel Centrum', '/', class: 'navbar-brand'
      .collapse.navbar-collapse#myNavbar
         %ul.nav.navbar-nav
            %li.rooms= link_to "#{t 'nav.rooms'}", rooms_path 
            %li.reservations= link_to "#{t 'nav.reservations'}", new_reservation_path
            %li.contact= link_to "#{t 'nav.contact'}", contact_path
            - if current_user
               %li.logout= link_to 'Logout', :logout, method: :post
            - else
               %li.user= link_to 'Login', :login
         %ul.nav.navbar-nav.navbar-right
            %li.dropdown
               %a.dropdown-toggle{'href'=>'#', 'data-toggle'=>'dropdown', 'role'=>'button', 'aria-haspopup'=>'true', 'aria-expanded'=>'false'} 
                  = image_tag('flags/blank.gif', id: 'curent-language', class: 'flag', alt: "#{t 'nav.language'}")
                  %span.caret
               %ul.dropdown-menu
                  %li#pl= link_to image_tag('flags/blank.gif', class: 'flag flag-pl', alt: 'PL'), language_path(:pl)
                  %li#gb= link_to image_tag('flags/blank.gif', class: 'flag flag-gb', alt: 'EN'), language_path(:gb)
                  %li#it= link_to image_tag('flags/blank.gif', class: 'flag flag-it', alt: 'IT'), language_path(:it)